name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: slimbean/arduino-cli:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Checkout SnappyProto
        uses: actions/checkout@v2
        with:
          repository: grafana/arduino-snappy-proto
          path: arduino-snappy-proto
      - name: Checkout PromLokiTransport
        uses: actions/checkout@v2
        with:
          repository: grafana/arduino-prom-loki-transport
          path: arduino-prom-loki-transport
          
      - name: Dump Config
        run: arduino-cli config dump --verbose
      
      - name: Install Board Managers
        run: |
          arduino-cli --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json core update-index
          arduino-cli --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json core install arduino:samd
          arduino-cli --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json core install esp32:esp32
      - name: Install Libraries
        run: |
          arduino-cli lib install ArduinoBearSSL MKRGSM ArduinoHttpClient WiFiNINA
      - name: Build MKRWIFI1010 Example 1
        run: |  
          arduino-cli compile --library $GITHUB_WORKSPACE --library $GITHUB_WORKSPACE/arduino-snappy-proto --library $GITHUB_WORKSPACE/arduino-prom-loki-transport --fqbn arduino:samd:mkrwifi1010 $GITHUB_WORKSPACE/examples/prom_01_local/prom_01_local.ino
      - name: Build MKRWIFI1010 Example 2
        run: |  
          arduino-cli compile --library $GITHUB_WORKSPACE --library $GITHUB_WORKSPACE/arduino-snappy-proto --library $GITHUB_WORKSPACE/arduino-prom-loki-transport --fqbn arduino:samd:mkrwifi1010 $GITHUB_WORKSPACE/examples/prom_02_grafana_cloud/prom_02_grafana_cloud.ino
      - name: Build MKRGSM1400 Example 1
        run: |  
          arduino-cli compile --library $GITHUB_WORKSPACE --library $GITHUB_WORKSPACE/arduino-snappy-proto --library $GITHUB_WORKSPACE/arduino-prom-loki-transport --fqbn arduino:samd:mkrgsm1400 $GITHUB_WORKSPACE/examples/prom_01_local/prom_01_local.ino
      - name: Build MKRGSM1400 Example 2
        run: |       
          arduino-cli compile --library $GITHUB_WORKSPACE --library $GITHUB_WORKSPACE/arduino-snappy-proto --library $GITHUB_WORKSPACE/arduino-prom-loki-transport --fqbn arduino:samd:mkrgsm1400 $GITHUB_WORKSPACE/examples/prom_02_grafana_cloud/prom_02_grafana_cloud.ino
      - name: Build ESP32 Pico Example 1
        run: |  
          arduino-cli compile --library $GITHUB_WORKSPACE --library $GITHUB_WORKSPACE/arduino-snappy-proto --library $GITHUB_WORKSPACE/arduino-prom-loki-transport --fqbn esp32:esp32:pico32 $GITHUB_WORKSPACE/examples/prom_01_local/prom_01_local.ino
      - name: Build ESP32 Pico Example 2
        run: |      
          arduino-cli compile --library $GITHUB_WORKSPACE --library $GITHUB_WORKSPACE/arduino-snappy-proto --library $GITHUB_WORKSPACE/arduino-prom-loki-transport --fqbn esp32:esp32:pico32 $GITHUB_WORKSPACE/examples/prom_02_grafana_cloud/prom_02_grafana_cloud.ino
